#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

global.loadInput = () => {
  const primaryInput = path.resolve(__dirname, process.argv[2].replace('.js', '.in'));
  const secondaryInput = path.resolve(__dirname, path.dirname(process.argv[2]), 'first.in');
  if (fs.existsSync(primaryInput)) return fs.readFileSync(primaryInput, 'utf8');
  if (fs.existsSync(secondaryInput)) return fs.readFileSync(secondaryInput, 'utf8');
  throw new Error('Failed to find input file for current run');
};

String.prototype.lines = function() {
  return this.split('\n');
};

require(path.resolve(__dirname, process.argv[2]));
